// Hand-curated pronunciation respellings provided by the app owner.
// Keys are lowercase; values are phonetic respellings used for TTS only
// (the on-screen text is never changed). This is the single source of truth
// for proper-noun pronunciation — see lib/speechPronounce.js.

export const CURATED_DICT = {
  "jesus christ": "jee-zuss kryste",
  jesus: "jee-zuss",
  christ: "kryste",
  matthew: "math-yoo",
  saint: "saynt",
  david: "day-vid",
  abraham: "ay-bruh-ham",
  isaac: "eye-zuck",
  jacob: "jay-kub",
  judas: "joo-duh",
  phares: "fair-eez",
  zara: "zeer-uh",
  thamar: "tay-mar",
  esrom: "hez-ron",
  aram: "air-um",
  aminadab: "uh-min-uh-dab",
  naasson: "nak-shon",
  salmon: "sam-un",
  booz: "boh-az",
  rachab: "ray-hab",
  obed: "oh-bed",
  ruth: "rooth",
  jesse: "jess-ee",
  solomon: "sol-uh-mun",
  urias: "yoo-rye-uh",
  roboam: "ree-uh-boh-um",
  abia: "uh-bye-uh",
  asa: "ay-suh",
  josaphat: "joh-suh-fat",
  joram: "jor-um",
  ozias: "uh-zye-uh",
  joatham: "joh-uh-thum",
  achaz: "ay-kaz",
  ezekias: "hez-ih-kye-uh",
  manasses: "muh-nass-uh",
  amon: "ay-mon",
  josias: "joh-sye-uh",
  jechonias: "jek-uh-nye-uh",
  babylon: "bab-ih-lun",
  salathiel: "shee-al-tee-el",
  zorobabel: "zuh-rub-uh-bel",
  abiud: "ab-ee-yood",
  eliakim: "ih-lye-uh-kim",
  azor: "ay-zor",
  sadoc: "zay-dok",
  achim: "ay-kim",
  eliud: "ell-ee-yood",
  eleazar: "ell-ee-ay-zur",
  matthan: "math-un",
  joseph: "joh-zif",
  mary: "mair-ee",
  emmanuel: "ih-man-yoo-el",
  "holy ghost": "hoh-lee gohst",
  lord: "lord",
};