// Hand-curated pronunciation respellings provided by the app owner.
// Keys are lowercase; values are phonetic respellings used for TTS only
// (the on-screen text is never changed). This is the single source of truth
// for proper-noun pronunciation — see lib/speechPronounce.js.

export const CURATED_DICT = {
  "jesus christ": "jee-zuss kryst",
  jesus: "jee-zuss",
  christ: "kryst",
  david: "day-vid",
  abraham: "ay-bruh-ham",
  isaac: "eye-zuck",
  jacob: "jay-kub",
  judas: "joo-duss",
  phares: "fair-eez",
  zara: "zeh-ruh",
  thamar: "thay-mar",
  esrom: "ez-rom",
  aram: "air-um",
  aminadab: "uh-min-uh-dab",
  naasson: "nay-uh-son",
  salmon: "sam-un",
  booz: "boh-uhz",
  rachab: "ray-kab",
  obed: "oh-bed",
  ruth: "rooth",
  jesse: "jess-ee",
  solomon: "sol-uh-mun",
  urias: "yoo-rye-us",
  roboam: "roh-boh-um",
  abia: "uh-bye-uh",
  asa: "ay-suh",
  josaphat: "joh-suh-fat",
  joram: "jor-um",
  ozias: "oh-zye-us",
  joatham: "joh-uh-thum",
  achaz: "ay-kaz",
  ezekias: "ee-zi-kye-us",
  manasses: "muh-nass-eez",
  amon: "ay-mon",
  josias: "joh-sye-us",
  jechonias: "jek-uh-nye-us",
  babylon: "bab-ih-lun",
  salathiel: "suh-lay-thee-el",
  zorobabel: "zuh-roh-buh-bel",
  abiud: "uh-bye-ood",
  eliakim: "ih-lye-uh-kim",
  azor: "ay-zor",
  sadoc: "zay-dok",
  achim: "ay-kim",
  eliud: "ell-ee-yood",
  eleazar: "ell-ee-ay-zur",
  matthan: "math-un",
  joseph: "joez-uf",
  mary: "mair-ee",
  emmanuel: "ih-man-yoo-el",
  "holy ghost": "hoh-lee gohst",
  lord: "lord",
};