// Fix pronunciation of archaic King James English words for text-to-speech.
// Many TTS voices mispronounce "-eth" / "-est" endings (e.g. "abideth" read as
// "abi-DETH" instead of "a-BIDE-eth"). We respell affected words phonetically
// for SPEECH ONLY — the on-screen text is never changed.
//
// Strategy:
//  1. A small dictionary handles irregular/common words exactly.
//  2. A general rule respells remaining "...eth" / "...est" words by inserting
//     a soft vowel so the ending is voiced as a separate syllable ("-uth").
//
// Case is preserved (Abideth → Abideth respelled, ABIDETH → upper) so the
// utterance still flows naturally.

// Exact respellings for frequent words (lowercase keys).
const DICT = {
  abideth: 'abydeth',
  believeth: 'be-leev-uth',
  receiveth: 'reseeveth',
  liveth: 'liv-uth',
  giveth: 'giv-uth',
  loveth: 'luv-uth',
  doeth: 'doo-uth',
  goeth: 'go-uth',
  knoweth: 'no-uth',
  saith: 'seth',
  hath: 'hath',
  doth: 'duth',
  cometh: 'cum-uth',
  dwelleth: 'dwel-uth',
  walketh: 'wawk-uth',
  worketh: 'wurk-uth',
  speaketh: 'speek-uth',
  seeketh: 'seek-uth',
  keepeth: 'keep-uth',
  maketh: 'make-uth',
  taketh: 'take-uth',
  bringeth: 'bring-uth',
  sitteth: 'sit-uth',
  standeth: 'stand-uth',
  runneth: 'run-uth',
  endureth: 'en-dure-uth',
  reigneth: 'rain-uth',
  judgeth: 'juj-uth',
  hopeth: 'hope-uth',
  beareth: 'bare-uth',
  doest: 'doo-est',
  knowest: 'no-est',
  believest: 'be-leev-est',
  livest: 'liv-est',
  comest: 'cum-est',
  goest: 'go-est',
  shouldest: 'should-est',
  wouldest: 'would-est',
  couldest: 'could-est',
  hadst: 'had-st',
  wast: 'wost',
  shalt: 'shalt',
  wilt: 'wilt',

  // Archaic pronouns / particles
  unto: 'untoo',
  thou: 'thow',
  thee: 'thee',
  thy: 'thy',
  thine: 'thine',
  ye: 'yee',
  hast: 'hast',
  art: 'art',
  ere: 'air',
  thence: 'thents',
  hence: 'hents',
  whence: 'wents',
  thither: 'thith-er',
  hither: 'hith-er',
  whither: 'with-er',
  yea: 'yay',
  nay: 'nay',
  verily: 'vair-il-ee',
  behold: 'be-hold',
  wherefore: 'where-for',
  therefore: 'there-for',
  henceforth: 'hents-forth',
  forasmuch: 'for-az-much',
  peradventure: 'per-ad-ven-cher',
  notwithstanding: 'not-with-stan-ding',

  // Frequently mispronounced KJB names / words
  selah: 'see-lah',
  amen: 'ah-men',
  hallelujah: 'hal-eh-loo-yah',
  cherubim: 'chair-oo-bim',
  cherubims: 'chair-oo-bims',
  seraphim: 'sair-uh-fim',
  ephod: 'ee-fod',
  shekel: 'shek-uhl',
  shekels: 'shek-uhls',
  bdellium: 'duh-lih-um',
  raca: 'rah-kah',
  selvedge: 'sel-vij',
  habergeon: 'hab-er-jun',
  scapegoat: 'scape-goat',
  firmament: 'fur-muh-ment',
  countenance: 'coun-ten-ents',
  levitical: 'leh-vit-ih-kul',
  levite: 'lee-vite',
  levites: 'lee-vites',

  // Frequently mispronounced proper names (people)
  melchizedek: 'mel kiz a deck',
  melchisedec: 'mel kiz a deck',
  nebuchadnezzar: 'neb-oo-kad-nez-er',
  abednego: 'a-bed-nee-go',
  shadrach: 'shad-rak',
  meshach: 'mee-shak',
  methuselah: 'meh-thoo-zeh-lah',
  mahalaleel: 'ma-hal-a-leel',
  jehoshaphat: 'jeh-hosh-a-fat',
  zerubbabel: 'zeh-rub-a-bel',
  artaxerxes: 'ar-ta-zerk-seez',
  ahasuerus: 'a-haz-yoo-ee-rus',
  belteshazzar: 'bel-teh-shaz-er',
  belshazzar: 'bel-shaz-er',
  zacchaeus: 'za-kee-us',
  caiaphas: 'kay-a-fas',
  barabbas: 'ba-rab-as',
  bartholomew: 'bar-thol-o-mew',
  zebedee: 'zeb-eh-dee',
  nicodemus: 'nik-o-dee-mus',
  zacharias: 'zak-a-rye-as',
  zechariah: 'zek-a-rye-ah',
  jeremiah: 'jair-eh-my-ah',
  isaiah: 'eye-zay-ah',
  hezekiah: 'hez-eh-kye-ah',
  habakkuk: 'ha-bak-uk',
  haggai: 'hag-eye',
  malachi: 'mal-a-kye',
  nehemiah: 'nee-eh-my-ah',
  obadiah: 'o-ba-dye-ah',
  ahithophel: 'a-hith-o-fel',
  mephibosheth: 'meh-fib-o-sheth',
  abimelech: 'a-bim-eh-lek',
  jeroboam: 'jair-o-bo-am',
  rehoboam: 'ree-ho-bo-am',
  uzziah: 'uh-zye-ah',
  manasseh: 'ma-nas-eh',
  caesar: 'see-zer',
  herodias: 'heh-ro-dee-as',
  theophilus: 'thee-of-il-us',
  onesimus: 'o-nes-i-mus',
  apollos: 'a-pol-os',
  priscilla: 'pri-sil-ah',
  aquila: 'ak-wil-ah',

  // Frequently mispronounced place names
  gethsemane: 'geth-sem-a-nee',
  golgotha: 'gol-go-thah',
  capernaum: 'ka-per-nay-um',
  bethsaida: 'beth-say-da',
  gennesaret: 'geh-nes-a-ret',
  philippi: 'fil-ip-eye',
  thessalonica: 'thes-a-lo-nye-ka',
  colosse: 'ko-los-ee',
  laodicea: 'lay-od-i-see-ah',
  ephesus: 'ef-eh-sus',
  galatia: 'ga-lay-sha',
  cilicia: 'si-lish-ah',
  pamphylia: 'pam-fil-ee-ah',
  cappadocia: 'kap-a-do-shah',
  mesopotamia: 'mes-o-po-tay-mee-ah',
  euphrates: 'yoo-fray-teez',
  gilead: 'gil-ee-ad',
  bethlehem: 'beth-leh-hem',
  nazareth: 'naz-a-reth',
  jericho: 'jair-i-ko',
  sychar: 'sye-kar',
  areopagus: 'air-ee-op-a-gus',
  patmos: 'pat-mos',
  decapolis: 'deh-cap-o-lis',
  gadara: 'gad-a-rah',
  gadarenes: 'gad-a-reens',
  gergesenes: 'gur-geh-seens',
  emmaus: 'eh-may-us',
  cyrene: 'sye-ree-nee',
  derbe: 'dur-bee',
  lystra: 'lis-trah',
  iconium: 'eye-ko-nee-um',
  attalia: 'at-a-lye-ah',
  troas: 'tro-az',
  berea: 'beh-ree-ah',
  cenchrea: 'sen-kree-ah',
  miletus: 'my-lee-tus',
  syracuse: 'sir-a-kews',
  rhegium: 'ree-jee-um',
  puteoli: 'pew-tee-o-lye',
  appii: 'ap-ee-eye',
  gomorrah: 'go-mor-ah',
  zoar: 'zo-ar',
  succoth: 'suk-oth',
  peniel: 'pen-ee-el',
  mizpah: 'miz-pah',
  ebenezer: 'eb-en-ee-zer',
  gilgal: 'gil-gal',
  shiloh: 'shy-lo',
  kirjath: 'kir-jath',
  jearim: 'jee-a-rim',
  beersheba: 'beer-shee-bah',
  hebron: 'hee-bron',
  shechem: 'shek-em',
  samaria: 'sa-mair-ee-ah',
  galilee: 'gal-i-lee',
  judaea: 'joo-dee-ah',
  idumaea: 'id-yoo-mee-ah',
  perea: 'peh-ree-ah',
  ararat: 'air-a-rat',
  sinai: 'sye-nye',
  horeb: 'hor-eb',
  pisgah: 'piz-gah',
  nebo: 'nee-bo',
  carmel: 'kar-mel',
  tabor: 'tay-bor',
  hermon: 'hur-mon',
  kedron: 'ked-ron',
  siloam: 'sye-lo-am',
  aceldama: 'a-kel-da-mah',

  // More commonly mispronounced people
  abraham: 'aybruhham',
  isaac: 'eye-zak',
  jacob: 'jay-kub',
  esau: 'ee-saw',
  joseph: 'jo-zef',
  pharaoh: 'fair-o',
  potiphar: 'pot-i-far',
  zipporah: 'zi-por-ah',
  jethro: 'jeth-ro',
  korah: 'kor-ah',
  caleb: 'kay-leb',
  joshua: 'josh-oo-ah',
  rahab: 'ray-hab',
  achan: 'ay-kan',
  deborah: 'deb-or-ah',
  barak: 'bair-ak',
  gideon: 'gid-ee-un',
  jephthah: 'jef-thah',
  samson: 'sam-sun',
  delilah: 'deh-lye-lah',
  boaz: 'bo-az',
  naomi: 'nay-o-mee',
  elimelech: 'eh-lim-eh-lek',
  hannah: 'han-ah',
  eli: 'ee-lye',
  samuel: 'sam-yoo-el',
  saul: 'sawl',
  jonathan: 'jon-a-than',
  abner: 'ab-ner',
  joab: 'jo-ab',
  absalom: 'ab-sa-lom',
  bathsheba: 'bath-shee-bah',
  nathan: 'nay-than',
  solomon: 'sol-o-mun',
  elijah: 'eh-lye-jah',
  elisha: 'eh-lye-shah',
  ahab: 'ay-hab',
  jezebel: 'jez-eh-bel',
  naaman: 'nay-a-man',
  gehazi: 'geh-hay-zye',
  josiah: 'jo-sye-ah',
  jehoiakim: 'jeh-hoy-a-kim',
  zedekiah: 'zed-eh-kye-ah',
  daniel: 'dan-yel',
  ezekiel: 'eh-zee-kee-el',
  ezra: 'ez-rah',
  mordecai: 'mor-deh-kye',
  esther: 'es-ter',
  haman: 'hay-man',
  vashti: 'vash-tye',
  job: 'jobe',
  eliphaz: 'el-i-faz',
  bildad: 'bil-dad',
  zophar: 'zo-far',
  elihu: 'eh-lye-hew',
  hosea: 'ho-zay-ah',
  joel: 'jo-el',
  amos: 'ay-mos',
  jonah: 'jo-nah',
  micah: 'my-kah',
  nahum: 'nay-hum',
  zephaniah: 'zef-a-nye-ah',
  gabriel: 'gay-bree-el',
  michael: 'my-kel',
  elisabeth: 'eh-liz-a-beth',
  herod: 'hair-od',
  pilate: 'py-lit',
  judas: 'joo-das',
  iscariot: 'is-kair-ee-ut',
  matthias: 'ma-thye-as',
  thaddaeus: 'tha-dee-us',
  matthew: 'math-yoo',
  philip: 'fil-ip',
  thomas: 'tom-as',
  andrew: 'an-droo',
  simon: 'sye-mun',
  lazarus: 'laz-a-rus',
  martha: 'mar-thah',
  cornelius: 'kor-nee-lee-us',
  ananias: 'an-a-nye-as',
  sapphira: 'sa-fye-rah',
  gamaliel: 'ga-may-lee-el',
  barnabas: 'bar-na-bas',
  silas: 'sye-las',
  timotheus: 'tim-o-thee-us',
  timothy: 'tim-o-thee',
  titus: 'tye-tus',
  philemon: 'fye-lee-mon',
  felix: 'fee-lix',
  festus: 'fes-tus',
  agrippa: 'a-grip-ah',
  apollyon: 'a-pol-yon',

  // More commonly mispronounced words
  propitiation: 'pro-pish-ee-ay-shun',
  righteousness: 'rytchusness',
  righteous: 'rytchus',
  iniquity: 'i-nik-wi-tee',
  iniquities: 'i-nik-wi-teez',
  transgression: 'tranz-gresh-un',
  transgressions: 'tranz-gresh-unz',
  abomination: 'a-bom-i-nay-shun',
  circumcision: 'sir-kum-sizh-un',
  circumcised: 'sir-kum-syzd',
  tabernacle: 'tab-er-nak-ul',
  sanctuary: 'sank-choo-air-ee',
  sanctification: 'sank-ti-fi-kay-shun',
  propitious: 'pro-pish-us',
  censer: 'sen-ser',
  mercyseat: 'mur-see-seet',
  brimstone: 'brim-stone',
  leviathan: 'leh-vye-a-than',
  behemoth: 'beh-hee-moth',
  manna: 'man-ah',
  shewbread: 'show-bred',
  laver: 'lay-ver',
  ephah: 'ee-fah',
  homer: 'ho-mer',
  hin: 'hin',
  omer: 'o-mer',
  talents: 'tal-ents',
  publican: 'pub-li-kan',
  publicans: 'pub-li-kans',
  centurion: 'sen-toor-ee-un',
  proselyte: 'pros-eh-lite',
  synagogue: 'sin-a-gog',
  sanhedrim: 'san-heh-drim',
  pharisees: 'fair-i-seez',
  sadducees: 'sad-yoo-seez',
  scribes: 'skribes',
  phylacteries: 'fi-lak-ter-eez',
};

const matchCase = (orig, repl) => {
  if (orig === orig.toUpperCase()) return repl.toUpperCase();
  if (orig[0] === orig[0].toUpperCase()) return repl.charAt(0).toUpperCase() + repl.slice(1);
  return repl;
};

// Many TTS voices read a hyphen as a literal pause or spell the parts out
// letter-by-letter. Convert respelling hyphens to spaces so each syllable is
// spoken as a connected word part instead.
const deHyphen = (s) => s.replace(/-/g, ' ');

export function fixArchaicPronunciation(text = '') {
  return String(text).replace(/[A-Za-z]+/g, (word) => {
    const lower = word.toLowerCase();
    if (DICT[lower]) return matchCase(word, deHyphen(DICT[lower]));
    // General rule: words ending in "eth" (4+ letters) → voice the ending as a
    // soft "uth" syllable (e.g. "abideth" → "abide uth"), without a hyphen.
    if (lower.length > 4 && lower.endsWith('eth')) {
      return matchCase(word, lower.slice(0, -3) + ' uth');
    }
    // Words ending in "est" (5+ letters) → "est" as a clear separate syllable.
    if (lower.length > 5 && lower.endsWith('est')) {
      return matchCase(word, lower.slice(0, -3) + ' est');
    }
    return word;
  });
}